### ISSUE TITLE
Pretty Printing JSON in text mode

### ISSUE THREAD

**Issue by brendanmanning** [WoLfulus/zoya#3]
Hello!

My team and I are working to integrate zoya into our project.

We'd like to use JSON logs in prod (which I understand zoya has the capacity to do quite easily).
However, when we do local development in VSCode, we'd like to output to text mode.

The problem is that in text mode, objects are printed as `[zoya] » 🔵  info    [object Object]`

Is there any way to resolve this without having to manually encapsulate every instance of a logged object with `JSON.stringify`?

**Comment by WoLfulus** [comment]
I'm unable to do the proper change right now, but I'll check it out once I get home (probably next week)

:)

**Comment by brendanmanning** [comment]
I did a little digging into the codebase and think I got it!

Please see #4 for a potential solution
