### ISSUE TITLE
Add `success` type

### ISSUE THREAD

**Issue by gluons** [WoLfulus/zoya#46]
**Is your feature request related to a problem? Please describe.**
I want to print some `success` message but **zoya** don't have `success`.

https://github.com/WoLfulus/zoya/blob/282cdc67182e8956c5065020643675087aab29c3/examples/default.ts#L4-L9

**Describe the solution you'd like**
Please add `success` type.

**Additional context**
\-

**Comment by WoLfulus** [comment]
added.

**Comment by gluons** [comment]
Thank you very much. So fast. 🤩

**Comment by WoLfulus** [comment]
My pleasure!

**Comment by WoLfulus** [comment]
🤦‍♂️ Thanks!
